source 'http://gems.rubyforge.org'
gem 'rspec', '1.3.1'
gem 'echoe', '4.5.2'
gem 'rake'
gem 'dm-core', '1.0.2'
gem 'dm-aggregates', '1.0.2'
gem 'dm-migrations', '1.0.2'
gem 'dm-sqlite-adapter', '1.0.2'
